config/routes.rb
Rails.application.routes.draw do

  resources :bookings
  
  root 'bookings#index'

  get '/new_booking', to: 'bookings#create', as: :create
  
end

app/models/booking.rb
class Booking < ActiveRecord::Base
    
  validates :sender, :presence =>  {:booking => "Sender can't be blank." }, :length => { minimum: 1 }
  validates :recipient, :presence => true, :length => { minimum: 1 }
  validates :pickup_addr, :presence => true
  validates :dropoff_addr, :presence => true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new(:sender => cookies[:sender_name])
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
        cookies[:pickup_addr] = @booking.dropoff_addr
        cookies[:sender_name] = @booking.sender
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:booking_id, :sender, :recipient, :booking_date, :pickup_addr, :dropoff_addr, :delivered)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id="googleMap"></div>
<div class="form-group">
  <div class="field">
    <%= f.label :sender %><br>
    <%= f.text_field :sender, required: true %>
    <% unless @booking.errors[:sender].empty? %>
      <p class = "text-danger">
        <% @booking.errors.full_messages_for(:sender).each do |e| %>
          <%= e %> <br>
        <% end %>
      </p>
    <% end %>
  </div>
</div>
<div class="form-group">
  <div class="field">
    <%= f.label :recipient %><br>
    <%= f.text_field :recipient, required: true %>
    <% unless @booking.errors[:recipient].empty? %>
      <p class = "text-danger">
        <% @booking.errors.full_messages_for(:recipient).each do |e| %>
          <%= e %> <br>
        <% end %>
      </p>
    <% end %>
  </div>
</div>
<div class="form-group">
  <div class="address-field">
    Pick-up address<br>
    <% @value = cookies[:pickup_addr] %>
    <%= f.text_field :pickup_addr, required: true, :id => "pickup-address", :value => @value %>
    <% unless @booking.errors[:pickup_addr].empty? %>
      <p class = "text-danger">
        <% @booking.errors.full_messages_for(:pickup_addr).each do |e| %>
          <%= e %> <br>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

<div class="modal fade" id="timeModal"role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Your delivery estimation</h4>
      </div>
      <div class="modal-body">
        <div class="deliveryTime"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<div class="form-group">
  <div class="address-field">
    Drop-off address<br>
    <%= f.text_field :dropoff_addr, :id => "dropoff-address" %>
    <% unless @booking.errors[:dropoff_addr].empty? %>
      <p class = "text-danger">
        <% @booking.errors.full_messages_for(:dropoff_addr).each do |e| %>
          <%= e %> <br>
        <% end %>
      </p>
    <% end %>
    <a class ="btn btn-default distanceTimeBtn" data-toggle="modal" href="#timeModal">Display distance and time</a>
  </div>
</div>

<%= f.hidden_field :delivered, value: 'false' %>

<div class="form-group">
  <span class="btn-group">
    <%= f.submit :class => 'btn btn-primary' %>
  </span>
</div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<!-- 
  Booking Index
  created by: Minju Park
  last edited in 13/10/2016
-->


<p id="notice"><%= notice %></p>

<h1>On-demand courier Service</h1>
<h3>List of bookings made</h3>
<table>
  <thead>
    <tr>
      <th>Sender</th>
      <th>Recipient</th>
      <th>Booking date</th>
      <th>Pickup address</th>
      <th>Dropoff address</th>
      <th>Delivered</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.sender %></td>
        <td><%= booking.recipient %></td>
        <td><%= booking.created_at %></td>
        <td><%= booking.pickup_addr %></td>
        <td><%= booking.dropoff_addr %></td>
        <td><%= booking.delivered %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 <%= link_to 'Create', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<!-- 
  Showing Booking 
  created by: Minju Park
  last edited in 13/10/2016
-->

<p id="notice"><%= notice %></p>

<p>
  <strong>Sender:</strong>
  <%= @booking.sender %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @booking.recipient %>
</p>


<p>
  <strong>Pickup address:</strong>
  <%= @booking.pickup_addr %>
</p>

<p>
  <strong>Dropoff address:</strong>
  <%= @booking.dropoff_addr %>
</p>


<%= link_to 'Back', bookings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC6f1YBcLl99UiOtUoP8M1bzmszakh56jA&libraries=places"></script>
  
  <%= csrf_meta_tags %>
  
  
</head>
<body>

<%= yield %>

</body>
</html>